services:
  db:
    image: postgres:latest
    container_name: postgres_whatsapp_grcp
    environment:
      POSTGRES_USER: postgres_whatsapp
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: whatsapp_grpc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:alpine
    container_name: redis_whatsapp_grcp
    ports:
      - "6379:6379"

volumes:
  postgres_data:
